config/routes.rb
MechTurk::Application.routes.draw do

  resources :advertisements
  resources :answers
  resources :users

  root :to => "users#new"

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  attr_accessible :description, :name, :image_url

  validates_presence_of :name, :image_url

  has_one :question
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :quality_response, :quantity_response, :question_id, :user_id

  validates :quality_response, :presence => true,
            :length => {:maximum => 10}
  validates :quantity_response, :presence => true,
            :length => {:maximum => 10}

  validates :question_id, :presence => true
  validates :user_id, :presence => true

  belongs_to :question
  belongs_to :user
end

app/models/international.rb
class International < ActiveRecord::Base
  COUNTRIES = [
  "Select Your Country",
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua And Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegowina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, the Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard and McDonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of",
  "Korea, Republic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia, The Former Yugoslav Republic Of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory, Occupied",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Barthelemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan, Province of China",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe"
]
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :advertisement_id, :quantity_question, :quality_question

  validates :quantity_question, :presence => true
  validates :quality_question, :presence => true

  belongs_to :advertisement
  has_many :answers

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :country, :answer_count, :worker_id

  validates_presence_of :country
  validates_uniqueness_of :worker_id

  has_many :answers

end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  def index
    @advertisements = Advertisement.all
  end

  def show
    @advertisement = Advertisement.find(params[:id])
    @answer = Answer.new
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    redirect_to "/" and return if User.last.answers.count > 2
    Answer.create(
      :quality_response => params[:answer][:quality_response],
      :quantity_response => params[:answer][:quantity_response],
      :question_id => params[:answer][:question_id],
      :user_id => User.last.id
      )
    redirect_to "/advertisements/#{get_random_advertisement}"
  end

  def get_random_advertisement
    number_of_advertisements = Advertisement.all.count
    rand(number_of_advertisements) + 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose :user

  def create
    if user.save
      redirect_to advertisements_path
    else
      render :new
    end
  end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/advertisements/index.html.haml
.hero-unit
  %h1#welcome-title The Psychology of Advertising
  %h3 Welcome to the Advertisement Index Page
  %p#psych-image
    =image_tag "psychology_logo.png"

%p.thumbnails
  -@advertisements.each do |advertisement|
    =link_to(image_tag(advertisement.image_url), advertisement_path(advertisement))

app/views/advertisements/show.html.haml
=link_to(image_tag(@advertisement.image_url), @advertisement.image_url)
%p=@advertisement.name
%p=@advertisement.description

-unless @advertisement.question == nil
  =form_for @answer do |f|
    %p
      ="Question:"
      =@advertisement.question.quantity_question
    %p
      =f.label :quantity_response, "Answer:"
      =f.text_field :quantity_response
    %p
      ="Question:"
      =@advertisement.question.quality_question
    %p
      =f.label :quality_response, "Answer:"
      =f.text_field :quality_response
      =f.hidden_field :question_id, :value => @advertisement.id
    %p
      =f.submit

app/views/answers/create.html.haml
%h1 Answers#create
%p Find me in app/views/answers/create.html.haml

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title Psychology of Advertisement
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title= content_for?(:title) ? yield(:title) : "MechTurk"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="assets/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"} P of A
          .nav-collapse
            %ul.nav
              %li.active
                %a{:href => "#"} Home
              %li
                %a{:href => "#about"} About
              %li
                %a{:href => "#contact"} Contact
    .container
      = yield
      %footer
        %p &copy; 2013

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/users/new.html.haml
!!! 5
.hero-unit
  %h1#welcome-title
    Psychology of Advertisement
  %p Effective advertising appeals to three innate emotions.
  %h4 Love - Anger - Fear
  %p#psych-image
    =image_tag "psychology_logo.png"
  =form_for user, url: users_path, html: { class: "form-inline", id: "new-user-form" } do |f|
    =f.text_field :worker_id, class: "input-small", placeholder: "Worker ID"
    =f.collection_select :country, International::COUNTRIES, :to_s, :to_s, selected: "Select Your Country"
    =f.submit "Take Survey", class: "btn"

%h3#message Attract - Focus - Remember - Action
.row
  .span3
    %h2 Attract
    %p Attract a consumer's attention. The advertisement should visually stand out and speak to the consumer. Step one is to draw the consumer to the message.
  .span3
    %h2 Focus
    %p Focus the engaged consumer on a given message. When the consumer is engaged, it is important that the advertisement retains their attention for the duration of the message.
  .span3
    %h2 Remember
    %p Ensure that the consumer remembers the message. Uniqueness and repetition are great ways to make an imprint on a consumer. It is important that the consumer remembers the message when it's time for action.
  .span3
    %h2 Action
    %p Propel the consumer to take the desired action. The whole effectiveness of the ad is determined on the ability of the advertisement to act as a catalyst - causing the consumer to take an action.
%hr/